// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/finza-dashboard/Current.tsx": () => import("../components/mockups/finza-dashboard/Current.tsx"),
  "./components/mockups/finza-dashboard/ModernDashboard.tsx": () => import("../components/mockups/finza-dashboard/ModernDashboard.tsx"),
  "./components/mockups/templates/MonochromeLandscapePhotographyPortfolio-FNZNWh/Lp14.tsx": () => import("../components/mockups/templates/MonochromeLandscapePhotographyPortfolio-FNZNWh/Lp14.tsx"),
  "./components/mockups/templates/MonochromeLandscapePhotographyPortfolio-GIjrGW/Lp14.tsx": () => import("../components/mockups/templates/MonochromeLandscapePhotographyPortfolio-GIjrGW/Lp14.tsx"),
  "./components/mockups/templates/MonochromeLandscapePhotographyPortfolio-LeZL0M/Lp14.tsx": () => import("../components/mockups/templates/MonochromeLandscapePhotographyPortfolio-LeZL0M/Lp14.tsx"),
  "./components/mockups/templates/MonochromeLandscapePhotographyPortfolio-TDkUIV/Lp14.tsx": () => import("../components/mockups/templates/MonochromeLandscapePhotographyPortfolio-TDkUIV/Lp14.tsx"),
  "./components/mockups/templates/MonochromeLandscapePhotographyPortfolio-_Y9znl/Lp14.tsx": () => import("../components/mockups/templates/MonochromeLandscapePhotographyPortfolio-_Y9znl/Lp14.tsx"),
  "./components/mockups/templates/MonochromeLandscapePhotographyPortfolio-kKofKs/Lp14.tsx": () => import("../components/mockups/templates/MonochromeLandscapePhotographyPortfolio-kKofKs/Lp14.tsx")
};
